---
title: "Midterm"
format: 
  pdf:
    papersize: legal
editor: visual
---

Name:$\rule{6cm}{0.15mm}$ Student ID: $\rule{4cm}{0.15mm}$

1.  A supermarket wants to decide whether or not to carry a new brand of salsa and uses a free taste-test stand in the store.

    a.  What is the population being studied? \vspace{2cm}
    b.  What is the sampling method being used? \vspace{2cm}
    c.  What is the sample? \vspace{2cm}

2.  The United States accounted for 23.9% of all imported cars in 2017. The list below gives the percentage of total imported cars that were imported by the next highest 14 countries.

    |     |     |     |     |     |
    |-----|-----|-----|-----|-----|
    | 7.8 | 6.6 | 5.9 | 4.6 | 4.1 |
    | 3.8 | 2.7 | 2.3 | 1.7 | 1.5 |

    a.  Create a stem and leaf of the data. Comment on the shape and any important features. \vspace{10cm}
    b.  Calculate the mean. \vspace{4cm}
    c.  Calculate the standard deviation. \vspace{10cm}
    d.  Calculate the median and quartiles. \vspace{5cm}
    e.  Are there any outliers? Show all work. \vspace{5cm}
    f.  Create a boxplot. Comment on the shape and any important features. \vspace{7cm}

3.  Consider a woman whose brother is afflicted with hemophilia, which implies that the woman's mother has the hemophilia gene on one of her two X chromosomes (almost surely not both, since that is generally fatal). Thus there is a probability of 0.5 that the woman's mother has passed on the bad gene to her. The woman has two sons, each of whom will independently inherit the gene from one of her two chromosomes. If the woman herself has a bad gene, there is a 0.5 probability she will pass this on to a son. Suppose that neither of her two sons is afflicted with hemophilia.

    a.  What is the probability that the woman is indeed the carrier of the hemophilia gene? \vspace{7cm}
    b.  What is this probability if she has a third son who is also not afflicted? \vspace{7cm}

4.  A small manufacturing company will start operating a night shift. There are 20 machinists employed by the company.

    a.  If a night crew consists of 3 machinists, how many different crews are possible? \vspace{4cm}
    b.  If the machinists are ranked 1, 2, ..., 20 in order of competence, how many of these crews would not have the best machinist? \vspace{4cm}
    c.  How many of the crews would have at least 1 of the 10 best machinists? \vspace{4cm}
    d.  If one of these crews is selected at random to work on a particular night, what is the probability that the best machinist will not work that night? \vspace{4cm}

5.  Suppose we are interested in the number of even numbers showing when a pair of standard six-sided die are rolled.

    a.  Create the PMF. \vspace{7cm}

6.  Take the PMF shown below to answer the following questions.

    a.  Find the cdf. \vspace{7cm}
    b.  What is the mean of X? \vspace{5cm}
    c.  What is the standard deviation of X? \vspace{7cm}
    d.  What is the moment generating function of X? Use it to find the third moment. 
